InstitutoITLA/Models/Estudiantes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InstitutoITLA.Models
{
    public class Estudiantes
    {
        public int EstudiantesID { get; set; }
        [Required(ErrorMessage = "Matricula Requerida")]
        public string Matricula { get; set; }
        [Required(ErrorMessage = "Nombre Requerido ")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Apellido Requerido ")]
        public string Apellido { get; set; }
    }
}

InstitutoITLA/Controllers/EstudiantesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InstitutoITLA.Models;

namespace InstitutoITLA.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly ITLAContext _context;

        public EstudiantesController(ITLAContext context)
        {
            _context = context;
        }
        // GET: Estudiantes
        public async Task<IActionResult> MenuEs(string nombre)
        {
            var filter = _context.Estudiantes.Where(s => s.Nombre.Contains(nombre));
            if (nombre != null)
            {

                return View(filter);
            }

            return View(await _context.Estudiantes.ToListAsync());


        }

        // GET: Estudiantes/Detalle/ID
        public async Task<IActionResult> DetalleEs(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiantes = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.EstudiantesID == id);
            if (estudiantes == null)
            {
                return NotFound();
            }

            return View(estudiantes);
        }

        // GET: Estudiantes/Create
        public IActionResult CrearEs()
        {
            return View();
        }

        // POST: Estudiantes/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearEs([Bind("EstudiantesID,Matricula,Nombre,Apellido")] Estudiantes estudiantes)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiantes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(MenuEs));
            }
            return View(estudiantes);
        }

        // GET: Estudiantes/Editar/ID
        public async Task<IActionResult> EditarEs(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiantes = await _context.Estudiantes.FindAsync(id);
            if (estudiantes == null)
            {
                return NotFound();
            }
            return View(estudiantes);
        }

        // POST: Estudiantes/Editar/ID
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarEs(int id, [Bind("EstudiantesID,Matricula,Nombre,Apellido")] Estudiantes estudiantes)
        {
            if (id != estudiantes.EstudiantesID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiantes);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudiantesExists(estudiantes.EstudiantesID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(MenuEs));
            }
            return View(estudiantes);
        }

        // GET: Estudiantes/Borrar/ID
        public async Task<IActionResult> BorrarEs(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiantes = await _context.Estudiantes
                .FirstOrDefaultAsync(m => m.EstudiantesID == id);
            if (estudiantes == null)
            {
                return NotFound();
            }

            return View(estudiantes);
        }

        // POST: Estudiantes/Borrar/ID
        [HttpPost, ActionName("BorrarEs")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estudiantes = await _context.Estudiantes.FindAsync(id);
            _context.Estudiantes.Remove(estudiantes);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(MenuEs));
        }

        private bool EstudiantesExists(int id)
        {
            return _context.Estudiantes.Any(e => e.EstudiantesID == id);
        }
    }
}

InstitutoITLA/Views/Estudiantes/BorrarEs.cshtml
@model InstitutoITLA.Models.Estudiantes

@{
    ViewData["Title"] = "Eliminar";
}

    <br />  
<h3>¿Esta seguro de eliminar este estudiante?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
    </dl>
    
    <form asp-action="BorrarEs">
        <input type="hidden" asp-for="EstudiantesID" />
        <a type="button" class="btn btn-success" asp-action="MenuEs">Cancelar</a> |
        <input type="submit" value="Eliminar" class="btn btn-danger" />

    </form>
</div>

InstitutoITLA/Views/Estudiantes/CrearEs.cshtml
@model InstitutoITLA.Models.Estudiantes

@{
    ViewData["Title"] = "Create";
}

<script src="https://kit.fontawesome.com/3c52229e0a.js" crossorigin="anonymous"></script>

<br />
<br />

<div class="card">
    <h3 class="card-header font-weight-bold text-uppercase py-4  text-center">
            Ingrese los datos del estudiante
    </h3>

</div>
<br />

<form asp-action="CrearEs" method="post">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Matricula" class="control-label"></label>
            <input asp-for="Matricula" class="form-control" />
            <span asp-validation-for="Matricula" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Apellido" class="control-label"></label>
            <input asp-for="Apellido" class="form-control" />
            <span asp-validation-for="Apellido" class="text-danger"></span>
        </div>
    </div>

    <a type="button" class="btn btn-success" asp-action="MenuEs">Volver atras </a> |
    <input type="submit" value="Crear" class="btn btn-primary" />
</form>

<div>

</div>

InstitutoITLA/Views/Estudiantes/DetalleEs.cshtml
@model InstitutoITLA.Models.Estudiantes

@{
    ViewData["Title"] = "Detalles";
}

    <br />
<div>
    <dl class="list-group">

        <span style="font-size:20px; text-align:center; ">
            <dt class="list-group-item active">
                Detalles del estudiante
            </dt>
        </span>
        <dt class = "list-group-item ">
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>
        <dd class = "list-group-item">
            @Html.DisplayFor(model => model.Matricula)
        </dd>
        <dt class = "list-group-item">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "list-group-item">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "list-group-item">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "list-group-item">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
    </dl>
</div>

<br />  
<div>
    <a type="button" class="btn btn-success" asp-action="MenuEs">Volver atras </a> |
    <a type="button" class="btn btn-danger" asp-action="EditarEs" asp-route-id="@Model.EstudiantesID">Editar</a>

</div>

InstitutoITLA/Views/Estudiantes/EditarEs.cshtml
@model InstitutoITLA.Models.Estudiantes

@{
    ViewData["Title"] = "Edit";
}

    <br />

<span style="font-size:20px; text-align:center; ">
    <dt class="list-group-item active">
        Editar estudiates
    </dt>
</span>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarEs">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EstudiantesID" />
            <div class="form-group">
                <label asp-for="Matricula" class="list-group-item font-weight-bold"></label>
                <input asp-for="Matricula" class="form-control" />
                <span asp-validation-for="Matricula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="list-group-item font-weight-bold"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="list-group-item font-weight-bold" ></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a type="button" class="btn btn-success" asp-action="MenuEs">Cancelar</a> |
                <input type="submit" value="Guardar" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

InstitutoITLA/Views/Estudiantes/MenuEs.cshtml
@model IEnumerable<InstitutoITLA.Models.Estudiantes>

@{
    ViewData["Title"] = "Estudiante";
}
<form method="get" action=@Url.Action("MenuEs", "Estudiantes" )>
    <div class="form-group">
        @Html.TextBox("nombre", null, new
        {
            placeholder = "Buscar Por Nombre",

        })
        <button class="btn btn-info" type="submit">Buscar</button>
    </div>
</form>
<br />
<span class="table-add float-right mb-3 mr-2">
    <a asp-action="CrearEs" class="text-success">
        Crear Estudiante
        <i class="fas fa-plus fa-2x" aria-hidden="true"></i>
    </a>
</span>
<br />
<br />
<br />

<div class="card">
    <h3 class="card-header font-weight-bold text-uppercase py-4  text-center">
        Estudiantes

    </h3>

</div>


<div class="card-body">
    <div class="table-responsive">
        <div id="table" class="table-editable">

            <table class="table table-bordered table-responsive-md table-striped text-center">
                <thead>
                    <tr>
                        <th class="text-center">@Html.DisplayNameFor(model => model.Matricula)</th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.Nombre)</th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.Apellido)</th>
                        <th class="text-center">Detalles</th>
                        <th class="text-center">Opciones</th>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Matricula)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Apellido)
                            </td>
                            <td>
                                <!--Primer boton -->
                                <span class="table-up">
                                    <a asp-action="DetalleEs" asp-route-id="@item.EstudiantesID" class="indigo-text">
                                        <span style="font-size:25px; color: green; ">
                                            <i class="fas fa-info"
                                               aria-hidden="true"></i>
                                        </span>
                                    </a>
                                </span>
                            </td>
                            <td>
                                <!--Segundo boton -->
                                <span style="font-size: 25px; color: Dodgerblue; margin:2px;">
                                    <a asp-action="EditarEs" asp-route-id="@item.EstudiantesID" class="fas fa-edit"></a>
                                </span>

                                <!--Tercer boton -->
                                <span style="font-size: 25px; color:red;">
                                    <a asp-action="BorrarEs" asp-route-id="@item.EstudiantesID">
                                        <span style="font-size: 25px; color: red; margin:2px;">
                                            <i class="fas fa-trash-alt"></i>
                                        </span>
                                    </a>
                                </span>
                            </td>
                        </tr>
                    }
                </tbody>


            </table>
        </div>
    </div>
</div>
<!-- Editable table -->