InstitutoITLA/Models/Asignaturas.cs
using InstitutoITLA.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InstitutoITLA.Models
{
    public class Asignaturas
    {
        public int AsignaturasID { get; set; }
        [Required(ErrorMessage = "Nombre Requerido ")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Tipo Requerido ")]
        public string TipoDeAsignatura { get; set; }
        public virtual ICollection<AsignaturasMaestros> AsignaturasMaestros { get; set; }
        public virtual ICollection<AsignaturasEstudiantes> AsignaturasEstudiantes { get; set; }
    }
}

InstitutoITLA/Controllers/AsignaturasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InstitutoITLA.Models;

namespace InstitutoITLA.Controllers
{
    public class AsignaturasController : Controller
    {
        private readonly ITLAContext _context;

        public AsignaturasController(ITLAContext context)
        {
            _context = context;
        }

        // GET: Asignaturas
        public async Task<IActionResult> InicioAsgt(string nombre)
        {
            if (nombre != null)
            {
                var filter = _context.Asignaturas.Where(s => s.Nombre.Contains(nombre));
                return View(filter);
            }
            return View(await _context.Asignaturas.ToListAsync());
        }

        // GET: Asignaturas/Details/ID
        public async Task<IActionResult> DetalleAsgt(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asignaturas = await _context.Asignaturas
                .FirstOrDefaultAsync(m => m.AsignaturasID == id);
            if (asignaturas == null)
            {
                return NotFound();
            }

            return View(asignaturas);
        }

        // GET: Asignaturas/Create
        public IActionResult CrearAsgt()
        {
            return View();
        }

        // POST: Asignaturas/Crear
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CrearAsgt([Bind("AsignaturasID,Nombre,TipoDeAsignatura")] Asignaturas asignaturas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(asignaturas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(InicioAsgt));
            }
            return View(asignaturas);
        }

        // GET: Asignaturas/Edit/ID
        public async Task<IActionResult> EditarAsgt(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asignaturas = await _context.Asignaturas.FindAsync(id);
            if (asignaturas == null)
            {
                return NotFound();
            }
            return View(asignaturas);
        }

        // POST: Asignaturas/Edit/ID
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarAsgt(int id, [Bind("AsignaturasID,Nombre,TipoDeAsignatura")] Asignaturas asignaturas)
        {
            if (id != asignaturas.AsignaturasID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asignaturas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AsignaturasExists(asignaturas.AsignaturasID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(InicioAsgt));
            }
            return View(asignaturas);
        }

        // GET: Asignaturas/Delete/ID
        public async Task<IActionResult> BorrarAsgt(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asignaturas = await _context.Asignaturas
                .FirstOrDefaultAsync(m => m.AsignaturasID == id);
            if (asignaturas == null)
            {
                return NotFound();
            }

            return View(asignaturas);
        }

        // POST: Asignaturas/Delete/ID
        [HttpPost, ActionName("BorrarAsgt")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asignaturas = await _context.Asignaturas.FindAsync(id);
            _context.Asignaturas.Remove(asignaturas);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(InicioAsgt));
        }

        private bool AsignaturasExists(int id)
        {
            return _context.Asignaturas.Any(e => e.AsignaturasID == id);
        }
    }
}

InstitutoITLA/Views/Asignaturas/BorrarAsgt.cshtml
@model InstitutoITLA.Models.Asignaturas

@{
    ViewData["Title"] = "Borrar";
}

<br />
<h3>¿Esta seguro de eliminar esta asignatura    ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TipoDeAsignatura)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TipoDeAsignatura)
        </dd>
    </dl>

    <form asp-action="BorrarAsgt">
        <input type="hidden" asp-for="AsignaturasID" />
        <a type="button" class="btn btn-success" asp-action="InicioAsgt">Cancelar</a> |
        <input type="submit" value="Eliminar" class="btn btn-danger" />

    </form>
</div>

InstitutoITLA/Views/Asignaturas/CrearAsgt.cshtml
@model InstitutoITLA.Models.Asignaturas

@{
    ViewData["Title"] = "Crear Asignatura";
}

<script src="https://kit.fontawesome.com/3c52229e0a.js" crossorigin="anonymous"></script>

<br />
<br />

<div class="card">
    <h3 class="card-header font-weight-bold text-uppercase py-4  text-center">
        Ingrese los datos de la asignatura
    </h3>

</div>
<br />
<form asp-action="CrearAsgt">
    <div class="form-row">
        <div class="form-group col-md-6">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" />
            <span asp-validation-for="Nombre" class="text-danger"></span>
        </div>
        <div class="form-group col-md-6">
            <label asp-for="TipoDeAsignatura" class="control-label"></label>
            <input asp-for="TipoDeAsignatura" class="form-control" />
            <span asp-validation-for="TipoDeAsignatura" class="text-danger"></span>
        </div>
    </div>
    <a type="button" class="btn btn-success" asp-action="InicioAsgt">Volver atras </a> |
    <input type="submit" value="Crear" class="btn btn-primary" />
</form>

<div>

</div>

InstitutoITLA/Views/Asignaturas/DetalleAsgt.cshtml
@model InstitutoITLA.Models.Asignaturas

@{
    ViewData["Title"] = "Detalle";
}

<br />
<div>
    <dl class="list-group">

        <span style="font-size:20px; text-align:center; ">
            <dt class="list-group-item active">
                Detalles de la asignatura
            </dt>
        </span>
        <dt class="list-group-item ">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="list-group-item">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="list-group-item">
            @Html.DisplayNameFor(model => model.TipoDeAsignatura)
        </dt>
        <dd class="list-group-item">
            @Html.DisplayFor(model => model.TipoDeAsignatura)
        </dd>
    </dl>
</div>

<br />
<div>
    <a type="button" class="btn btn-success" asp-action="InicioAsgt">Volver atras </a> |
    <a type="button" class="btn btn-danger" asp-action="EditarAsgt" asp-route-id="@Model.AsignaturasID">Editar</a>

</div>

InstitutoITLA/Views/Asignaturas/EditarAsgt.cshtml
@model InstitutoITLA.Models.Asignaturas

@{
    ViewData["Title"] = "Editar Asignatura";
}

<br />

<span style="font-size:20px; text-align:center; ">
    <dt class="list-group-item active">
        Editar asignatura
    </dt>
</span>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarAsgt">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AsignaturasID" />
            <div class="form-group">
                <label asp-for="Nombre" class="list-group-item font-weight-bold"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoDeAsignatura" class="list-group-item font-weight-bold"></label>
                <input asp-for="TipoDeAsignatura" class="form-control" />
                <span asp-validation-for="TipoDeAsignatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a type="button" class="btn btn-success" asp-action="InicioAsgt">Cancelar</a> |
                <input type="submit" value="Guardar" class="btn btn-danger" />
            </div>
        </form>
    </div>
</div>

InstitutoITLA/Views/Asignaturas/InicioAsgt.cshtml
@model IEnumerable<InstitutoITLA.Models.Asignaturas>

@{
    ViewData["Title"] = "Asignatura";
}

    <form method="get" action=@Url.Action("InicioAsgt", "Asignaturas" )>
        <div class="form-group">

            @Html.TextBox("nombre", null, new
            {
                placeholder = "Buscar Por Nombre",

            })
            <button class="btn btn-info" type="submit">Buscar</button>
        </div>

    </form>
<br />
<span class="table-add float-right mb-3 mr-2">
    <a asp-action="CrearAsgt" class="text-success">
        Crear Asignatura
        <i class="fas fa-plus fa-2x" aria-hidden="true"></i>
    </a>
</span>
<br />
<br />
<br />

<div class="card">
    <h3 class="card-header font-weight-bold text-uppercase py-4  text-center">
        Asignaturas

    </h3>

</div>



<div class="card-body">
    <div class="table-responsive">
        <div id="table" class="table-editable">

            <table class="table table-bordered table-responsive-md table-striped text-center">
                <thead>
                    <tr>
                        <th class="text-center">@Html.DisplayNameFor(model => model.Nombre)</th>
                        <th class="text-center">@Html.DisplayNameFor(model => model.TipoDeAsignatura)</th>
                        <th class="text-center">Detalles</th>
                        <th class="text-center">Opciones</th>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TipoDeAsignatura)
                            </td>
                            <td>
                                <!--Primer boton -->
                                <span class="table-up">
                                    <a asp-action="DetalleAsgt" asp-route-id="@item.AsignaturasID" class="indigo-text">
                                        <span style="font-size:25px; color: blue; ">
                                            <i class="fas fa-info"
                                               aria-hidden="true"></i>
                                        </span>
                                    </a>
                                </span>
                            </td>
                            <td>
                                <!--Segundo boton -->
                                <span style="font-size: 25px; color: Dodgerblue; margin:2px;">
                                    <a asp-action="EditarAsgt" asp-route-id="@item.AsignaturasID" class="fas fa-edit"></a>
                                </span>

                                <!--Tercer boton -->
                                <span style="font-size: 25px; color:red;">
                                    <a asp-action="BorrarAsgt" asp-route-id="@item.AsignaturasID">
                                        <span style="font-size: 25px; color: red; margin:2px;">
                                            <i class="fas fa-trash-alt"></i>
                                        </span>
                                    </a>
                                </span>
                            </td>
                        </tr>
                    }
                </tbody>


            </table>

        </div>
    </div>
</div>
<!-- Editable table -->